// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  file: src/stack/nginx/server.coffee
  //  package: ws-rmi-examples

  var Stack_RMI_Server, options, server;

  ({Stack_RMI_Server} = require('../stack_rmi_server'));

  ({options} = require('../settings'));

  server = new Stack_RMI_Server(options.ipc);

  module.exports = server;

}).call(this);
