// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  file: src/examples/stack/browser/client.coffee
  //  package: ws-rmi-examples

  var Stack_RMI_Client, client, options;

  ({Stack_RMI_Client} = require('../stack_rmi_client'));

  ({options} = require('../settings'));

  client = new Stack_RMI_Client(options.remote_client);

  if (typeof window !== "undefined" && window !== null) {
    window.client = client;
  } else {
    module.exports = client;
  }

}).call(this);
