// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  file: src/stack/browser/index.coffee
  //  package: ws-rmi-examples

  var client;

  client = require('./client');

  exports.client = client;

}).call(this);
