// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee
  var ipc, tcp;

  ipc = require('./ipc');

  tcp = require('./tcp');

  exports.ipc = ipc;

  exports.tcp = tcp;

}).call(this);
