// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  logger.coffee

  var Logger, util;

  util = require('util');

  Logger = class Logger {
    constructor(options) {
      this.options = {
        colors: (options != null ? options.colors : void 0) || true,
        depth: (options != null ? options.depth : void 0) || null
      };
    }

    log(...xs) {
      var i, len, results, x;
      console.log("\n");
      results = [];
      for (i = 0, len = xs.length; i < len; i++) {
        x = xs[i];
        if (typeof x === 'string') {
          results.push(console.log(x));
        } else {
          results.push(console.log(util.inspect(x, this.options)));
        }
      }
      return results;
    }

  };

  exports.Logger = Logger;

}).call(this);
