// Generated by CoffeeScript 2.5.1
(function() {
  //  -*- coffee -*-

  //  file: src/stack/stack_rmi_object.coffee
  //  package: ws-rmi-examples

  var Stack, Stack_RMI_Object, Stack_RMI_Stub, WS_RMI_Object, WS_RMI_Stub;

  ({Stack} = require('./stack'));

  
  ({WS_RMI_Object, WS_RMI_Stub} = require('ws-rmi/common'));

  Stack_RMI_Object = class Stack_RMI_Object extends WS_RMI_Object {
    constructor(options = {}) {
      var method_names, stack;
      stack = new Stack();
      method_names = ['push', 'pop'];
      super('stack', stack, method_names, options);
    }

  };

  Stack_RMI_Stub = class Stack_RMI_Stub extends WS_RMI_Stub {
    constructor(options = {}) {
      var objects;
      objects = [];
      super(objects, options);
    }

  };

  exports.Stack_RMI_Object = Stack_RMI_Object;

  exports.Stack_RMI_Stub = Stack_RMI_Stub;

}).call(this);
