// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  file: src/examples/stack/ipc/index.coffee
  //  package: ws-rmi-examples

  var client, server;

  client = require('./client');

  server = require('./server');

  exports.client = client;

  exports.server = server;

}).call(this);
