// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  file: src/stack/tcp/server.coffee
  //  package: ws-rmi-examples

  var Stack_RMI_Server, options, server;

  ({Stack_RMI_Server} = require('../stack_rmi_server'));

  options = require('./options');

  server = new Stack_RMI_Server(options);

  module.exports = server;

}).call(this);
