// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  file: /src/stack/ipc/client.coffee
  //  package: ws-rmi-examples

  var Stack_RMI_Client, client, options;

  ({Stack_RMI_Client} = require('../stack_rmi_client'));

  options = require('./options');

  client = new Stack_RMI_Client(options);

  module.exports = client;

}).call(this);
