// Generated by CoffeeScript 2.5.1
(function() {
  //!/usr/bin/env coffee

  //  settings.coffee

  var log, log_options, options, util;

  util = require('util');

  log_options = {
    colors: true,
    depth: null
  };

  log = function(...xs) {
    var i, len, results, x;
    console.log("\n");
    results = [];
    for (i = 0, len = xs.length; i < len; i++) {
      x = xs[i];
      if (typeof x === 'string') {
        results.push(console.log(x));
      } else {
        results.push(console.log(util.inspect(x, log_options)));
      }
    }
    return results;
  };

  // Unix IPC options
  // Used by server and CLI client

  options = {
    protocol: 'ws+unix',
    port: null,
    host: null,
    uid: void 0, // defaults to user starting server
    gid: 33, // group 'www-data'
    mode: 0o660,
    path: 'tmp/stack-rmi',
    log_level: 2,
    log: log
  };

  module.exports = options;

}).call(this);
